from .auth_view import auth_bp
from .book_genre_view import book_genre_bp
from .book_img_view import book_img_bp
from .book_keyword_view import book_keyword_bp
from .book_kind_view import book_kind_bp
from .book_view import book_bp
from .saved_book_view import saved_book_bp
from .search_view import search_bp
from .user_view import user_bp
